version: "2.0"
services:
  mysql:
    image: mysql
    container_name: databaseMysql
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viewerDb
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend-fast-api:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: backend-fast-api
    restart: unless-stopped
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./backend:/fastapi
    networks:
      - app-network

  frontend-vue-js:
    stdin_open: true
    container_name: frontend-vue-js
    ports:
      - "8080:8080"
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/app
      - /app/node_modules
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin-viewer
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 1111:80
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-viewer
    restart: unless-stopped
    ports:
      - "90:90"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-fast-api
      - frontend-vue-js
      - phpmyadmin
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    external: true
