version: "2.0"
services:
  backend-fast-api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-fast-api
    restart: unless-stopped
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./backend:/fastapi
    networks:
      - app-network

  frontend-vue-js:
    stdin_open: true
    container_name: frontend-vue-js
    ports:
      - "8080:8080"
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/app
      - /app/node_modules
    networks:
      - app-network

  #Mysql DB
  mysql:
    image: mysql:8.0
    container_name: databaseMysql
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_USER: www-data
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viewerDb
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin-viewer
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 1111:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    external: true
